[pytest]
addopts = -q
filterwarnings =
    ignore:Please use `import python_multipart` instead.*:PendingDeprecationWarning
    ignore:Support for class-based `config` is deprecated.*:DeprecationWarning
    ignore:The `dict` method is deprecated.*:DeprecationWarning
    ignore:The Query.get\(\) method is considered legacy.*:DeprecationWarning
